<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=2"><title></title><meta content="width=device-width, initial-scale=2.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta name="viewport" content="width=device-width"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/assets/css/demo.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/assets/css/styles.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap-grid.min.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap-reboot.min.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/font-awesome.css" rel="stylesheet"><link rel="stylesheet" href="https://use.typekit.net/fio2tgl.css"></head><body><div id="navbar-full"><div class="container"><nav class="navbar navbar-fixed-top navbar-default" role="navigation"><div class="container"><div class="navbar-header"><button class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="index.html"><div class="logo-container"><div class="logo p-3"><img src="./assets/img/logo.png"></div><div class="brand">SIMSCONSULTANCY</div></div></a></div><div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"><ul class="nav navbar-nav navbar-right"><li><a href="<?php base_url();?>">Home</a></li><li><a href="<?php base_url();?>/services">Services</a></li><li><a href="<?php base_url();?>/esg">ESG</a></li><li><a href="<?php base_url();?>/about-us">About Us</a></li><li><a href="<?php base_url();?>/contact-us">Contact Us</a></li></ul></div></div></nav></div><div class="jumbotron text-left py-5" style="background-image: url('./assets/img/about-us-cover.png'); background-position:top center;"><div class="container"><div class="row text-white" style="background-color:transparent;"><div class="col-md-8 col-sm-12 p-2"><div class="col-md-12 text-white"><h1 class="jumbotron-heading mt-5"><strong class="d-sm-block w-100">Who We Are</strong></h1></div><div class="col-md-12 py-2"><p class="my-4">SIMS Corporate Governance and Compliance Consultancy is a specialis provider
of secretarial, corporate governance, compliance, training and confrence solution.</p><p class="my-4">We work together with boards, directors, and senior management to be most efficient
and to align organizations towards best practices and accountability.
All this is done within the confines of applicable regulation through a diligent and thorough
address of issues such as board committee composition, audit guidelines, and policy manual
development among others, both for public corporations and private sector players.</p><p class="my-4">We further provide platforms for proffesionals and acedamics to enhance their skills ans knowledge,
through corporate governance and compliance workshops, master classes, training confrences.</p><p class="my-4">Over and above our consultancy services, we organise and host training workshops,
master-class and various forums that are structured to address governance related issues.
The conceptualization of our forums is informed by thorough research on market trends and
demands to ensure we meet our client's needs in the most relevant manner.</p><p class="my-4">Our tean of proffesionals ensures that we continously improve the corporate governance
culture through a personalized and client-oriented approach.</p><p class="my-5">Although our foot-print is currently confined within the African continent, we are structured
to ensure that our activities will reach the entire global economies.</p></div></div></div></div></div></div><main class="main bg-light p-4"><div class="container"><div class="bg-light"><div class="row"><div class="tim-typo text-left col-12"><h1><strong>Reach Out Today</strong></h1><p class="mt-3">SIMS Advisory assists in the assessment of the effectiveness of the
governing body.Enter your e-mail address and we'll contact you</p></div><div class="col-md-9 col-sm-12"><form id="contact-form"><div class="row"><div class="form-group col-md-6 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="name" type="text" name="name" placeholder="Name..."></div><div class="form-group col-md-6 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="surname" type="text" name="name" placeholder="Surname..."></div></div><div class="row"><div class="form-group col-md-8 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="email" type="email" name="name" placeholder="Email..."></div><div class="from-group col-md-4 my-3 col-sm-12 mx-sm-auto"><button class="btn btn-block" id="contact-btn" type="submit">Submit</button></div></div></form></div></div></div></div></main><script src="<?php echo base_url(); ?>/jquery/jquery-1.10.2.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/bootstrap3/js/bootstrap.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-checkbox.js"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-radio.js"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-bootstrapswitch.js"></script><script src="<?php echo base_url(); ?>/assets/js/get-shit-done.js"></script><script src="<?php echo base_url(); ?>/assets/js/custom.js"></script></body></html>