<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=2"><title></title><meta content="width=device-width, initial-scale=2.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta name="viewport" content="width=device-width"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/assets/css/demo.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/assets/css/styles.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap-grid.min.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap-reboot.min.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/font-awesome.css" rel="stylesheet"><link rel="stylesheet" href="https://use.typekit.net/fio2tgl.css"></head><body><div id="navbar-full"><div class="container"><nav class="navbar navbar-fixed-top navbar-default" role="navigation"><div class="container"><div class="navbar-header"><button class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="index.html"><div class="logo-container"><div class="logo p-3"><img src="./assets/img/logo.png"></div><div class="brand">SIMSCONSULTANCY</div></div></a></div><div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"><ul class="nav navbar-nav navbar-right"><li><a href="<?php base_url();?>">Home</a></li><li><a href="<?php base_url();?>/services">Services</a></li><li><a href="<?php base_url();?>/esg">ESG</a></li><li><a href="<?php base_url();?>/about-us">About Us</a></li><li><a href="<?php base_url();?>/contact-us">Contact Us</a></li></ul></div></div></nav></div><div class="jumbotron py-5" style="background-image: url('./assets/img/esg-cover.png'); background-position:top center;"><div class="container"><div class="row text-black mb-4" style="background-color:transparent;"><div class="col-md-7 col-sm-12 p-2"><div class="col-md-12"><h1 class="jumbotron-heading mt-2"><strong class="d-sm-block w-100">Environmental, Social and Governance</strong></h1></div><div class="col-md-12"><p class="mt-3">We understand ESG as the bedrock of institutionalised accountable organisations
focusing on ethical leadership, legal compliance, risk management and social inclusion,
we work with our clients to develop bespoke ESG frameworks agile
enough to respond to both local and international factors.</p></div></div></div></div></div></div><main><div class="container-fluid" style="background-image: url('./assets/img/esg-cover-2.png'); background-position:top center; min-height:370px;"><div class="container p-5"><div class="row text-white mt-4 d-flex" style="background-color:transparent;"><div class="col-md-10 offset-md-1 align-items-center"><div class="col-md-12 mt-4"><h2 class="display-1 mt-2"><strong class="d-sm-block w-100">ESG Matters</strong></h2></div><div class="col-md-12 mt-4"><p class="mt-3 p-3">SIMS offers advisory services in ESG to organisations seeking to deploy capital or
receive capital for growth and impact investments. To build resilient organisations, to defend them
with ethical governance and to unlock value with smart ESG solutions. SIMS guide clients to
develop a custom made position on ESG matters based on a comprehensive understanding of
relevant factors,and opportunities. We embed ESG into business and decision-making processes
for precise solutions.</p></div></div></div></div></div><div class="container-fluid bg-dark pb-0"><div class="container"><div class="row mt-4" style="background-color:transparent;"><div class="col-md-8 offset-md-2 align-items-center bg-light service-img p-5"><div class="col-md-12"><h2 class="text-bold py-2 px-5"><strong class="d-sm-block w-100">Solutions</strong></h2></div><div class="col-md-12"><ul class="pt-3"><li><p class="text-bold">Development of end-to-end ESG management system throughoffering bespoke ESG framework,
policies and procedures;</p></li><li><p class="text-bold">Design of user-friendly proprietary assessment tools, data analysis and reporting;</p></li><li><p class="text-bold">Conduct Due Diligence on potential investments with rapidly deployed specific
and measurable corrective actions plan and value creation;</p></li><li><p class="text-bold">Investment monitoring for on-going management of ESG corrective action plan.</p></li><li><p class="text-bold">ESG reporting on fund or company level.</p></li><li><p class="text-bold">Portfolio evaluation for regular reviews or pre-exit preparedness.</p></li><li><p class="text-bold">We provide tailored ESG training at investment firms, fund managers and companies.</p></li><li><p class="text-bold">We conduct ESG audits to ensure clients remain compliant with investment mandates.</p></li><li><p class="text-bold">We assist our clients to bridge the information gap of impact investment and ESG
management. This is through our strong understanding of local content, gloval connections,
sector engagement and  deep domain expertise.</p></li></ul></div></div></div></div></div><div class="container-fluid" style="background-image: url('./assets/img/esg-cover-3.png'); background-position:top center; min-height:270px;"><div class="container p-5"><div class="row text-white mt-4 d-flex" style="background-color:transparent;"><div class="col-md-10 offset-md-1 align-items-center"><div class="col-md-12 mt-4"><h2 class="display-1 mt-2"><strong class="d-sm-block w-100">Our ESG Approach</strong></h2></div><div class="col-md-12 mt-4"><p class="mt-3 p-3">SIMS espouses an integrated approach that ensures effective inclusion of ESG into its clients' investment philosophy. Such an approach is aimed at mitigating against any ESG risk that may impact on the investment and other economic activities of the client company.</p></div></div></div></div></div><div class="bg-light"><div class="container p-5"><div class="row mt-4 d-flex" style="background-color:transparent;"><div class="col-md-12"><h2 class="mt-2 text-center display-4"><strong class="d-sm-block w-100">Our Approach In Steps</strong></h2></div><div class="col-md-12 mt-4"><img class="img-responsive" src="./assets/img/steps-of-approach.png"></div></div></div></div><div class="bg-dark"><div class="container p-5"><div class="row text-center d-flex"><div class="col-12 p-3"><p class="display-5">Sustainability and impact investment are critical.
To achieve this, we have embedded the following ESG themes in our approach</p></div><div class="col-12 p-5 align-items-center"><ul class="px-5"><li><p><span class="text-bold">Job Creation</span>- Sustainable economic achievement requires strategies for the
significant creation of stable jobs, entrepreneurship development,
scale up of small and mediun enterprise and skills development.</p></li><li><p><span class="text-bold">Inclusive Economic Prosperity</span>- Transfromed economic development, where investments not only deliver
higher risk-adjusted returns, but also inclusion of society,
leading to sustainable social and environmental impact.</p></li><li><p><span class="text-bold">Gender Equality</span>- An ethical basis to achieving mutually advancing economic success
through financial and economic inclusion of women as investors, entrepreneurs,employees and customers</p></li><li><p><span class="text-bold">Youth</span>- Remaining open to the creativity and skills of a large part of the population
to achieve a demographic dividend that creates a stable economy designed for growth.</p></li><li><p><span class="text-bold">Climate Change</span>- Through deliberate resouce efficiency strategies,
we assist our clients to explore noteworthy opportunities for investors to integrate
and employ alternative solutions for a more sustainable future with better cost-benefit
outcomes than conventional methods.</p></li></ul></div></div></div></div><div class="bg-light"><div class="container text-black py-4"><div class="row"><div class="tim-typo text-left col-12"><h1><strong>Reach Out Today</strong></h1><p class="mt-3">SIMS Advisory assists in the assessment of the effectiveness of the
governing body.Enter your e-mail address and we'll contact you</p></div><div class="col-md-9 col-sm-12"><form id="contact-form"><div class="row"><div class="form-group col-md-6 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="name" type="text" name="name" placeholder="Name..."></div><div class="form-group col-md-6 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="surname" type="text" name="name" placeholder="Surname..."></div></div><div class="row"><div class="form-group col-md-8 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="email" type="email" name="name" placeholder="Email..."></div><div class="from-group col-md-4 my-3 col-sm-12 mx-sm-auto"><button class="btn btn-block" id="contact-btn" type="submit">Submit</button></div></div></form></div></div></div></div></main><script src="<?php echo base_url(); ?>/jquery/jquery-1.10.2.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/bootstrap3/js/bootstrap.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-checkbox.js"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-radio.js"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-bootstrapswitch.js"></script><script src="<?php echo base_url(); ?>/assets/js/get-shit-done.js"></script><script src="<?php echo base_url(); ?>/assets/js/custom.js"></script></body></html>