<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=2"><title></title><meta content="width=device-width, initial-scale=2.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta name="viewport" content="width=device-width"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/assets/css/demo.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/assets/css/styles.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap-grid.min.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/bootstrap-reboot.min.css" rel="stylesheet"><link href="<?php echo base_url(); ?>/bootstrap3/css/font-awesome.css" rel="stylesheet"><link rel="stylesheet" href="https://use.typekit.net/fio2tgl.css"></head><body><div id="navbar-full"><div class="container"><nav class="navbar navbar-fixed-top navbar-default" role="navigation"><div class="container"><div class="navbar-header"><button class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="index.html"><div class="logo-container"><div class="logo p-3"><img src="./assets/img/logo.png"></div><div class="brand">SIMSCONSULTANCY</div></div></a></div><div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"><ul class="nav navbar-nav navbar-right"><li><a href="<?php base_url();?>">Home</a></li><li><a href="<?php base_url();?>/services">Services</a></li><li><a href="<?php base_url();?>/esg">ESG</a></li><li><a href="<?php base_url();?>/about-us">About Us</a></li><li><a href="<?php base_url();?>/contact-us">Contact Us</a></li></ul></div></div></nav></div><div class="jumbotron py-5" style="background-image: url('./assets/img/service-cover.png'); background-position:top center;"><div class="container"><div class="row text-white mb-4" style="background-color:transparent;"><div class="col-md-7 col-sm-12 p-2"><div class="col-md-12 my-2"><h1 class="display-4">Our Services</h1></div><div class="col-md-12"><h2 class="jumbotron-heading mt-2 display-1"><strong class="d-sm-block w-100">Corporate Governance Advisory Services</strong></h2></div><div class="col-md-12"><p class="mt-3">Considering the complex regualatory environment within which all organisations
in public and private operate whilst simultaneously being required to apply sound
governance practices and King IV recommendations. It goes without saying that the board,
its individual members, and those tasked with managing the affairs of the organisation,
including prescribed officers, are in need of experienced, and professional and practical support,
guidance and unique workable solutions. We provide such advisory services to aid those in
organisational leadership in achieving this objective.</p></div></div></div></div></div></div><main><div class="container-fluid"><div class="row d-flex align-items-center bg-light"><div class="col-md-4 offset-md-1 my-5 p-5 order-xs-1"><h1>Assessements/<br>Evaluations</h1><p class="my-5">SIMS Advisory assissts in the assessment of the effectiveness of the
governing body, it's committees and individual memebers and company
company secretaries by applying the best-suited methodology,
whether it is by way of an online questionnaire, personal-in-depth
interviews or group facilitation of a combination of several of these
methodologies dependent on the needs of the organisation.</p></div><div class="col-md-4 offset-md-2 service-img order-xs-0"><img class="img-responsive mr-5" src="./assets/img/service-ass-eval.png"></div></div><div class="row d-flex align-items-center bg-dark"><div class="col-md-4 offset-md-1 service-img"><img class="img-responsive" src="./assets/img/service-due-dil.png"></div><div class="col-md-4 offset-md-2 my-5 p-5"><h1>Due Dilligence</h1><p class="my-5 pr-5">We asses and report on the prevailing level of
corporate governance in a target organisation.
Our report includes findings and recommendations for implementation
and reassessment after initial implementations.</p></div></div><div class="row d-flex align-items-center bg-light"><div class="col-md-4 offset-md-1 my-5 p-5"><h1>Governance Audits</h1><p class="my-5">We conduct a gap analysis to establish the governance structure ,
chatters, terms of reference, delegations of authority, declaration of
interests and policies and procedures in place. The result is a findings
report with the fit-for-purpose recommendations and, once
implemented, a second audit to ensure correct application.</p></div><div class="col-md-4 offset-md-2 service-img"><img class="img-responsive mr-5" src="./assets/img/service-gov-aud.png"></div></div><div class="row d-flex align-items-center bg-dark"><div class="col-md-4 offset-md-1 service-img"><img class="img-responsive" src="./assets/img/service-gov-opi.png"></div><div class="col-md-4 offset-md-2 my-5 p-5"><h1>Governance Opinions</h1><p class="my-5 pr-5">As each scenerio is different we investigate the status and provide
organisation with legally sound governance opinion. As far as
possible it is our methodology to report on findings accompanied by
recommendations which can easily be practically implemented.</p></div></div><div class="row d-flex align-items-center bg-light"><div class="col-md-4 offset-md-1 my-5 p-5"><h1>Governance structures<br>and frameworks</h1><p class="my-5">SIMS team provides upstart guidance and advice on corporate
governance principles for all organisations, governing bodies, board
members and executives and company secretaries. Our team provides
guidance on the construction of an overall framework to achieve
sound governance practices.</p></div><div class="col-md-4 offset-md-2 service-img"><img class="img-responsive mr-5" src="./assets/img/service-gov-fra.png"></div></div></div><div class="bg-dark"><div class="container text-white py-4"><div class="row"><div class="tim-typo text-left col-12"><h1><strong>Reach Out Today</strong></h1><p class="mt-3">SIMS Advisory assists in the assessment of the effectiveness of the
governing body.Enter your e-mail address and we'll contact you</p></div><div class="col-md-9 col-sm-12"><form id="contact-form"><div class="row"><div class="form-group col-md-6 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="name" type="text" name="name" placeholder="Name..."></div><div class="form-group col-md-6 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="surname" type="text" name="name" placeholder="Surname..."></div></div><div class="row"><div class="form-group col-md-8 my-3 col-sm-12 mx-sm-auto"><input class="form-control" id="email" type="email" name="name" placeholder="Email..."></div><div class="from-group col-md-4 my-3 col-sm-12 mx-sm-auto"><button class="btn btn-block" id="contact-btn" type="submit">Submit</button></div></div></form></div></div></div></div></main><script src="<?php echo base_url(); ?>/jquery/jquery-1.10.2.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/bootstrap3/js/bootstrap.js" type="text/javascript"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-checkbox.js"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-radio.js"></script><script src="<?php echo base_url(); ?>/assets/js/gsdk-bootstrapswitch.js"></script><script src="<?php echo base_url(); ?>/assets/js/get-shit-done.js"></script><script src="<?php echo base_url(); ?>/assets/js/custom.js"></script></body></html>